version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data_email_service:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5435:5432

volumes:
  postgres_data_email_service:
